using System.Collections.Frozen;
using System.Collections.Generic;
using KdyPojedeVlak.Web.Engine.Djr;

namespace KdyPojedeVlak.Web.Models;

public static class DisplayConsts
{
    public static readonly FrozenDictionary<TrainOperation, string> TrainOperationIcons = new Dictionary<TrainOperation, string>
    {
        { TrainOperation.Unknown, "" },
        { TrainOperation.StopRequested, "" },
        { TrainOperation.Customs, "🛂" },
        { TrainOperation.Other, "" },
        { TrainOperation.EmbarkOnly, "◗" },
        { TrainOperation.DisembarkOnly, "◖" },
        { TrainOperation.RequestStop, "⨯" },
        { TrainOperation.DepartOnArrival, "△" },
        { TrainOperation.DepartAfterDisembark, "⊥" },
        { TrainOperation.NoWaitForConnections, "☉" },
        { TrainOperation.Preheating, "" },
        { TrainOperation.Passthrough, "" },
        { TrainOperation.ConnectedTrains, "" },
        { TrainOperation.TrainConnection, "" },
        // TODO: Better symbol
        { TrainOperation.StopsAfterOpening, "⨹" },
        { TrainOperation.ShortStop, "▲" },
        { TrainOperation.HandicappedEmbark, "" },
        { TrainOperation.HandicappedDisembark, "" },
        { TrainOperation.WaitForDelayedTrains, "●" },
        { TrainOperation.OperationalStopOnly, "+" },
        { TrainOperation.NonpublicStop, "⟠" },

        { TrainOperation.ServiceStop, "" },
        { TrainOperation.SystemStop, "" },
        { TrainOperation.ReversingStop, "" },
        { TrainOperation.StopForReversingMove, "" },
        { TrainOperation.StopForLocomotiveToRunAround, "" },
        { TrainOperation.TechnicalCheck, "" },
        { TrainOperation.GaugeChange, "" },
        { TrainOperation.AttachEngine, "" },
        { TrainOperation.DetachEngine, "" },
        { TrainOperation.ChangeEngine, "" },
        { TrainOperation.AttachCoach, "" },
        { TrainOperation.DetachCoach, "" },
        { TrainOperation.AttachDetachCoach, "" },
        { TrainOperation.AttachTrain, "" },
        { TrainOperation.SplitTrain, "" },
        { TrainOperation.VehicleParking, "" },
        { TrainOperation.MailServices, "" },
        { TrainOperation.Shunting, "" },
        { TrainOperation.ShuntingService, "" },
        { TrainOperation.TerminalService, "" },
        { TrainOperation.DriverChange, "" },
        { TrainOperation.DriverBreak, "" },
        { TrainOperation.CrewChange, "" },
        { TrainOperation.Watering, "" },
        { TrainOperation.Cleaning, "" },
        { TrainOperation.AnimalTreating, "" },
        { TrainOperation.PerishableGoodsTreating, "" },
        { TrainOperation.AdministrativeOperations, "" },
        { TrainOperation.PhotoStop, "" },
        { TrainOperation.TrainWaiting, "" },
        { TrainOperation.SimpleBreakTest, "" },
        { TrainOperation.FullBreakTest, "" },
        { TrainOperation.TrainReportStop, "☎" },
        { TrainOperation.OtnChange, "" },
        { TrainOperation.FinalTechnicalCheck, "" },
        { TrainOperation.DeliveryManipulation, "" },
        { TrainOperation.DepartureWaitsForDispatcher, "" },
        { TrainOperation.DepartureViaShunting, "" },
        { TrainOperation.TimeOffsetLevelling, "" },
        { TrainOperation.SecondTrainInD3, "" },
        { TrainOperation.RegularEntryOnFullVehicleTrack, "◻" },
        { TrainOperation.RegularSimultaneousEntryOnFullVehicleTrack, "◻" },
        { TrainOperation.RegularEntryOnFullTrack, "◯" },
        { TrainOperation.CrossingTechnicalCheck, "" },
        { TrainOperation.TransitTechnicalCheck, "" },
        { TrainOperation.AllOperatorActionsCancelled, "" },
        { TrainOperation.InitialTechnicalCheck, "" },
        { TrainOperation.DepartureTechnicalCheck, "" },
        { TrainOperation.StopsOnlyInSomeDays, "" },
        { TrainOperation.StartOfPublicPusherService, "" },
        { TrainOperation.EndOfPublicPusherService, "" },
        { TrainOperation.WithoutPublicPusherService, "" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<TrainOperation, string> TrainOperationDescriptions = new Dictionary<TrainOperation, string>
    {
        { TrainOperation.Unknown, "" },
        { TrainOperation.StopRequested, "Nástup a výstup cestujících" },
        { TrainOperation.Customs, "Celní a pasové odbavení" },
        { TrainOperation.Other, "Jiný důvod pobytu" },
        { TrainOperation.EmbarkOnly, "Zastavení jen pro nástup" },
        { TrainOperation.DisembarkOnly, "Zastavení jen pro výstup" },
        { TrainOperation.RequestStop, "Zastavení jen na znamení" },
        { TrainOperation.DepartOnArrival, "Odjezd v čase příjezdu" },
        { TrainOperation.DepartAfterDisembark, "Odjezd hned po výstupu" },
        { TrainOperation.NoWaitForConnections, "Nečeká na žádné přípoje" },
        { TrainOperation.Preheating, "Předtápění" },
        { TrainOperation.Passthrough, "Průjezd" },
        { TrainOperation.ConnectedTrains, "Jízda spojených vlaků" },
        { TrainOperation.TrainConnection, "Návaznost" },
        { TrainOperation.StopsAfterOpening, "Zastavuje od otevření zastávky" },
        { TrainOperation.ShortStop, "Pobyt kratší než 1/2 minuty" },
        { TrainOperation.HandicappedEmbark, "Nástup osoby se sníženou mobilitou" },
        { TrainOperation.HandicappedDisembark, "Výstup osoby se sníženou mobilitou" },
        { TrainOperation.WaitForDelayedTrains, "Čekání na zpožděné vlaky" },
        { TrainOperation.OperationalStopOnly, "Zastavení jen z dopravních důvodů" },
        { TrainOperation.NonpublicStop, "Nezveřejněné zastavení" },
        { TrainOperation.ServiceStop, "Zastavení ze služebních důvodů dopravce" },
        { TrainOperation.SystemStop, "Pobyt z bezpečnostních důvodů" },
        { TrainOperation.ReversingStop, "Úvrať vlaku bez změny HV a LČ" },
        { TrainOperation.StopForReversingMove, "Úvrať vlaku se změnou HV nebo LČ" },
        { TrainOperation.StopForLocomotiveToRunAround, "Úvrať hnacího vozidla" },
        { TrainOperation.TechnicalCheck, "Technická prohlídka" },
        { TrainOperation.GaugeChange, "Změna rozchodu" },
        { TrainOperation.AttachEngine, "Přivěšení HV" },
        { TrainOperation.DetachEngine, "Odvěšení HV" },
        { TrainOperation.ChangeEngine, "Přepřah HV" },
        { TrainOperation.AttachCoach, "Přivěšení vozů k vlaku" },
        { TrainOperation.DetachCoach, "Odvěšení vozů z vlaku" },
        { TrainOperation.AttachDetachCoach, "Manipulace s vozy" },
        { TrainOperation.AttachTrain, "Připojení vlaku" },
        { TrainOperation.SplitTrain, "Rozdělení vlaku" },
        { TrainOperation.VehicleParking, "Parkování vlaku" },
        { TrainOperation.MailServices, "Manipulace s poštou" },
        { TrainOperation.Shunting, "Posun" },
        { TrainOperation.ShuntingService, "Služby posunu" },
        { TrainOperation.TerminalService, "Služby terminálu" },
        { TrainOperation.DriverChange, "Výměna lokomotivní čety – osa" },
        { TrainOperation.DriverBreak, "Přestávka LČ" },
        { TrainOperation.CrewChange, "Výměna vlakové čety" },
        { TrainOperation.Watering, "Doplnění vody" },
        { TrainOperation.Cleaning, "Čištění / dezinfekce" },
        { TrainOperation.AnimalTreating, "Ošetření rostlin a zvířat" },
        { TrainOperation.PerishableGoodsTreating, "Ošetření SNZ" },
        { TrainOperation.AdministrativeOperations, "Administrativní úkony" },
        { TrainOperation.PhotoStop, "Foto zastávka" },
        { TrainOperation.TrainWaiting, "Pobyt v souladu s národními pravidly" },
        { TrainOperation.SimpleBreakTest, "Jednoduchá zkouška brzdy" },
        { TrainOperation.FullBreakTest, "Úplná zkouška brzdy" },
        { TrainOperation.TrainReportStop, "Ohlašovací povinnost nařízena" },
        { TrainOperation.OtnChange, "Změna čísla vlaku" },
        { TrainOperation.FinalTechnicalCheck, "Konečná technická prohlídka" },
        { TrainOperation.DeliveryManipulation, "Manipulace se zásilkou" },
        { TrainOperation.DepartureWaitsForDispatcher, "Odjezd až po výpravě výpravčím" },
        { TrainOperation.DepartureViaShunting, "Vlak odjíždí z dopravního bodu cestou posunu" },
        { TrainOperation.TimeOffsetLevelling, "Pobyt k vyrovnání časového posunu" },
        { TrainOperation.SecondTrainInD3, "Povinnost jednat v dopravně D3 jako vlak druhý" },
        { TrainOperation.RegularEntryOnFullVehicleTrack, "Pravidelný vjezd na kolej obsazenou vozidly" },
        { TrainOperation.RegularSimultaneousEntryOnFullVehicleTrack, "Pravidelný vjezd na kolej obsazenou vozidly – současné vjezdy" },
        { TrainOperation.RegularEntryOnFullTrack, "Pravidelný vjezd na obsazenou kolej" },
        { TrainOperation.CrossingTechnicalCheck, "Přechodová technická prohlídka" },
        { TrainOperation.TransitTechnicalCheck, "Technicko přepravní prohlídka" },
        { TrainOperation.AllOperatorActionsCancelled, "Všechny úkony dopravce zrušeny" },
        { TrainOperation.InitialTechnicalCheck, "Výchozí technická prohlídka" },
        { TrainOperation.DepartureTechnicalCheck, "Nácestná technická prohlídka" },
        { TrainOperation.StopsOnlyInSomeDays, "Pobyt jen v určitých dnech" },
        { TrainOperation.StartOfPublicPusherService, "Začátek VPS" },
        { TrainOperation.EndOfPublicPusherService, "Konec VPS" },
        { TrainOperation.WithoutPublicPusherService, "Nevyužití VPS" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<CentralPttNote, string> CentralPttNoteDescriptions = new Dictionary<CentralPttNote, string>
    {
        { CentralPttNote.Unknown, "" },
        { CentralPttNote.Class12, "U vlaků kategorie Sp a Os – ve vlaku řazeny k sezení i vozy 1. vozové třídy" },
        { CentralPttNote.Class1, "Ve vlaku řazeny k sezení pouze vozy 1. vozové třídy" },
        { CentralPttNote.Class2, "U vlaků kategorie R a vyšší – ve vlaku řazeny k sezení pouze vozy 2. vozové třídy" },
        { CentralPttNote.SleepingCar, "Lůžkový vůz" },
        { CentralPttNote.CouchetteCar, "Lehátkový vůz" },
        { CentralPttNote.DirectCar, "Přímý vůz" },
        { CentralPttNote.Cars, "Vůz pro přepravu osobních automobilů a motocyklů" },
        { CentralPttNote.Disabled, "Vůz vhodný pro přepravu cestujících na vozíku, nebo vůz se zvedací plošinou; doporučeno objednání přepravy" },
        { CentralPttNote.Restaurant, "Restaurační vůz" },
        { CentralPttNote.Reservation, "Do označených vozů možno zakoupit místenku" },
        { CentralPttNote.ObligatoryReservation, "Povinná rezervace míst" },
        { CentralPttNote.Baggage, "Úschova během přepravy (do vyčerpání kapacity)" },
        { CentralPttNote.Bicycle, "Přeprava spoluzavazadel (do vyčerpání kapacity)" },
        { CentralPttNote.Transfer, "Nutno přestoupit" },
        { CentralPttNote.Refreshments, "Občerstvení (roznášková služba nebo samoobslužný automat)" },
        { CentralPttNote.Cafe, "Bistrovůz" },
        { CentralPttNote.BaggageReservation, "Úschova během přepravy s možností rezervace místa pro jízdní kolo" },
        { CentralPttNote.BaggageObligatoryReservation, "Úschova během přepravy s povinnou rezervací místa pro jízdní kolo" },
        { CentralPttNote.BicycleReservation, "Přeprava spoluzavazadel s možností rezervace místa pro jízdní kolo a cestujícího, v některých vlacích pouze pro jízdní kolo" },
        { CentralPttNote.BicycleObligatoryReservation, "Přeprava spoluzavazadel s povinnou rezervací místa pro jízdní kolo a cestujícího, v některých vlacích pouze pro jízdní kolo" },
        { CentralPttNote.PowerSocket, "Ve vlaku je řazen vůz s přípojkou 230 V" },
        { CentralPttNote.ReplacementBus, AlternativeTransportDescription },
        { CentralPttNote.Children, "Vůz nebo oddíly vyhrazené pro cestující s dětmi do 10 let" },
        { CentralPttNote.DisabledPlatform, "Vůz vhodný pro přepravu cestujících na vozíku, je nutné objednání přepravy" },
        { CentralPttNote.SelfService, "Samoobslužný způsob odbavení cestujících" },
        { CentralPttNote.NoBicycles, "Přeprava jízdních kol jako spoluzavazadel je vyloučena" },
        { CentralPttNote.HistoricTrain, "Historický vlak" },
        { CentralPttNote.WomenSectionCD, "Dámský oddíl (oddíl pro samostatně cestující ženy)" },
        { CentralPttNote.SilentSectionCD, "Tichý oddíl" },
        { CentralPttNote.WifiCD, "Ve vlaku je řazen vůz s bezdrátovým připojením k internetu" },
        { CentralPttNote.PortalCD, "Palubní portál" },
        { CentralPttNote.CinemaCD, "Dětské kino" },
        { CentralPttNote.ExcludedFromStateDiscount, "Ve vlaku neplatí zvláštní jízdné pro žáky a studenty 18–26 let a pro cestující 65+" },
        { CentralPttNote.IntegratedTransportSystem, "Vlak kategorie R a vyšší zařazený v integrovaném dopravním systému" },
        { CentralPttNote.DirectedBoarding, "Usměrněný nástup" },
        { CentralPttNote.NoWc, "Vlak není vybaven WC" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<CentralPttNote, string> CentralPttNoteIcons = new Dictionary<CentralPttNote, string>
    {
        { CentralPttNote.Unknown, "" },
        { CentralPttNote.Class12, "𝟣.𝟤." },
        { CentralPttNote.Class1, "𝟣." },
        { CentralPttNote.Class2, "𝟤." },
        { CentralPttNote.SleepingCar, "🛌\uFE0E" },
        { CentralPttNote.CouchetteCar, "⧦" },
        { CentralPttNote.DirectCar, "🚃\uFE0E" },
        { CentralPttNote.Cars, "🚗\uFE0E" },
        { CentralPttNote.Disabled, "♿\uFE0E" },
        { CentralPttNote.Restaurant, "🍴\uFE0E" },
        { CentralPttNote.Reservation, "𝗥" },
        { CentralPttNote.ObligatoryReservation, "R⃞" },
        { CentralPttNote.Baggage, "🛄\uFE0E" },
        { CentralPttNote.Bicycle, "🚲\uFE0E" },
        { CentralPttNote.Transfer, "◊" },
        { CentralPttNote.Refreshments, "🍸\uFE0E" },
        { CentralPttNote.Cafe, "☕\uFE0E" },
        { CentralPttNote.BaggageReservation, "🛄\uFE0E⃝" },
        { CentralPttNote.BaggageObligatoryReservation, "🛄\uFE0E" },
        { CentralPttNote.BicycleReservation, "🚲\uFE0E⃝" },
        { CentralPttNote.BicycleObligatoryReservation, "🚲\uFE0E⃞" },
        { CentralPttNote.PowerSocket, "⚇\uFE0E" },
        { CentralPttNote.ReplacementBus, AlternativeTransportIcon },
        { CentralPttNote.Children, "𝗗" },
        { CentralPttNote.DisabledPlatform, "♿\uFE0E⃞" },
        { CentralPttNote.SelfService, "👁\uFE0E" },
        { CentralPttNote.NoBicycles, "🚲\uFE0E̸" },
        { CentralPttNote.HistoricTrain, "🚂\uFE0E" },
        { CentralPttNote.WomenSectionCD, "👩\uFE0E" },
        { CentralPttNote.SilentSectionCD, "🤫\uFE0E" },
        { CentralPttNote.WifiCD, "𝗐𝗂𝖿𝗂" },
        { CentralPttNote.PortalCD, "⏵⃞" },
        { CentralPttNote.CinemaCD, "𝗸𝗶𝗻𝗼" },
        { CentralPttNote.ExcludedFromStateDiscount, "⏺" },
        { CentralPttNote.IntegratedTransportSystem, "⇔" },
        { CentralPttNote.DirectedBoarding, "⛝" },
        { CentralPttNote.NoWc, "𝗐̵𝖼̵" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<TrainCategory, string> TrainCategoryNames = new Dictionary<TrainCategory, string>
    {
        { TrainCategory.Unknown, "" },
        { TrainCategory.EuroCity, "EC" },
        { TrainCategory.Intercity, "IC" },
        { TrainCategory.Express, "Ex" },
        { TrainCategory.EuroNight, "EN" },
        { TrainCategory.Regional, "Os" },
        { TrainCategory.SuperCity, "SC" },
        { TrainCategory.Rapid, "Sp" },
        { TrainCategory.FastTrain, "R" },
        { TrainCategory.RailJet, "rj" },
        { TrainCategory.Rex, "Rx" },
        { TrainCategory.TrilexExpres, "TLX" },
        { TrainCategory.Trilex, "TL" },
        { TrainCategory.LeoExpres, "LE" },
        { TrainCategory.Regiojet, "RJ" },
        { TrainCategory.ArrivaExpress, "AEx" },
        { TrainCategory.NightJet, "NJ" },
        { TrainCategory.LeoExpresTenders, "LET" },
        { TrainCategory.EuroSleeper, "ES" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<TrafficType, string> TrafficTypeNames = new Dictionary<TrafficType, string>
    {
        { TrafficType.Unknown, "" },
        { TrafficType.Os, "Osobní vlak" },
        { TrafficType.Ex, "Expres" },
        { TrafficType.R, "Rychlík" },
        { TrafficType.Sp, "Spěšný vlak" },
        { TrafficType.Sv, "Soupravový vlak" },
        { TrafficType.Nex, "Expresní nákladní vlak" },
        { TrafficType.Pn, "Průběžný nákladní vlak" },
        { TrafficType.Mn, "Manipulační vlak" },
        { TrafficType.Lv, "Lokomotivní vlak" },
        { TrafficType.Vleč, "Vlečkový vlak" },
        { TrafficType.Služ, "Služební vlak" },
        { TrafficType.Pom, "Nutný pomocný vlak" },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<SubsidiaryLocationType, string> SubsidiaryLocationTypeNames = new Dictionary<SubsidiaryLocationType, string>
    {
        { SubsidiaryLocationType.Unknown, "" },
        { SubsidiaryLocationType.None, "" },
        { SubsidiaryLocationType.StationTrack, "kolej " },
    }.ToFrozenDictionary();

    public static readonly FrozenDictionary<string, string> PublicTransportNames = new Dictionary<string, string>
    {
        { "9", "PID" },
        { "10", "PID" },
        { "11", "PID P" },
        { "12", "PID B" },
        { "13", "PID 0" },
        { "17", "PID 12" },
        { "18", "PID 11" },
        { "19", "PID 10" },
        { "20", "Stč" },
        { "21", "PID 1" },
        { "22", "PID 2" },
        { "23", "PID 3" },
        { "24", "PID 4" },
        { "25", "PID 5" },
        { "26", "PID 6" },
        { "27", "PID 7" },
        { "28", "PID 8" },
        { "29", "PID 9" },
        { "30", "IDS JK" },
        { "31", "IDS TA" },
        { "32", "IDPK" },
        { "33", "IDS P" },
        { "41", "IDOK" },
        { "42", "DÚK" },
        { "51", "IDOL" },
        { "52", "IREDO HK" },
        { "53", "VYDIS PU" },
        { "54", "VYDIS PU DD" },
        { "55", "IREDO PU" },
        { "56", "IREDO+JMK" },
        { "57", "IREDO+IDOL" },
        { "58", "IREDO+VYDIS" },
        { "61", "VDV" },
        { "64", "JMK" },
        { "71", "IDSOK" },
        { "72", "ZID" },
        { "73", "TZK" },
        { "74", "ID ZK" },
        { "80", "ODIS" },
        { "97", "IREDO PU DD" },
        { "98", "IREDO-" },
    }.ToFrozenDictionary();

    public const string PublicTransportServiceIcon = "🏛\uFE0E";
    public const string PublicTransportCompanyIcon = "🏢\uFE0E";
    public const string InconsistentTimeIcon = "◪";
    public const string AlternativeTransportIcon = "🚌\uFE0E";

    public const string PublicTransportServiceDescription = "Veřejná služba";
    public const string AlternativeTransportDescription = "Náhradní autobusová doprava";
    public const string InconsistentTimeDescription = "Nenavazující čas příjezdu a odjezdu";
}